### PR TITLE
Improve TestServer, fix topic and stream update, make tests parallel

### LINKED ISSUE #188: Ensure that the data is permanently removed from streams, topics etc.
Along with all the related components such as consumer groups, offsets and the others.

### PR DESCRIPTION
**Pull request by hubcio**
Instead of sleeping, we poll on bind().
This way, it's exactly known when it's possible
to start server for testing purposes.

When server is stared, we wait till it's bound
to all sockets.

All tests are started in parallel.

IggyClient is properly logged out upon drop.

Besides that, fixes #188.

### CODE REVIEW

File: integration/tests/cmd/stream/test_stream_delete_command.rs [hunk 1]
```diff
@@ -1,46 +1,37 @@
...
 use async_trait::async_trait;
+use iggy::client::Client;
 use iggy::streams::create_stream::CreateStream;
-use iggy::streams::get_stream::GetStream;
-use iggy::{client::Client, identifier::Identifier};
+use iggy::streams::get_streams::GetStreams;
 use predicates::str::diff;
 use serial_test::serial;
 
-enum TestStreamId {
```
Comment (BartoszCiesla) [inline integration/tests/cmd/stream/test_stream_delete_command.rs:10]: This is used in one file but with tests which are under development it will be used in multiple files - I propose to keep it here.

Comment (hubcio) [reply integration/tests/cmd/stream/test_stream_delete_command.rs:10]: I didn't change the code, just renamed files.

**Review by spetz — APPROVED** [review]
This is a massive improvement in terms of the overall test execution time, well done :D
