### PR TITLE
fix(connectors): support default credential provider chain for iceberg sink

### LINKED ISSUE #2911: Support default credential provider chain for Iceberg sink storage authentication
### Description

While configuring the Iceberg sink connector in Iggy Connectors, I noticed that the configuration currently requires explicitly providing storage credentials:

```
store_access_key_id = "admin"
store_secret_access_key = "password"
```

If these fields are not provided, the connector fails during initialization with an error such as:

```
Failed to parse configuration for sink connector with ID: 1.
missing field `store_access_key_id`
```

**Logs:**
```
ERROR connector: connector_target="iggy_connector_sdk::sink" Failed to parse configuration for sink connector with ID: 1. missing field `store_access_key_id`
ERROR iggy_connectors::sink: Plugin initialization failed (ID: 1)
ERROR iggy_connectors::sink: Failed to initialize sink container with name: Iceberg sink (iceberg)
```

In many production environments (e.g., AWS, Kubernetes), it is considered best practice to avoid static access keys and instead rely on the default credential provider chain, such as:

- IAM roles
- Instance profiles
- Workload identity
- Environment credentials

**Suggested Improvement**

Add support for using the default credential provider chain for storage authentication.

### Component

Connectors

### PR DESCRIPTION
**Pull request by gomnitrix**
## Which issue does this PR close?

Closes #2911

## Rationale

Production environments prefer the default credential provider chain over static keys, which the Iceberg Sink connector currently lacks support for.
## What changed?

The Iceberg Sink connector previously failed to initialize if `store_access_key_id` and `store_secret_access_key` were missing from the config, blocking the use of standard identity-based auth. This fix makes these config fields optional, allowing the underlying OpenDAL seamlessly fall back to the default credential provider chain. An isolated integration test was also added to verify this fallback behavior using environment variables.

## Local Execution

- Passed
- Pre-commit hooks ran

### E2E Validation Results

The fallback mechanism has been verified through:

**1. Automated Integration Test**
Added a new test fixture: `IcebergEnvAuthFixture` and a corresponding integration test case: `iceberg_sink_uses_default_credential_chain`. It simulates the environment by omitting config credentials, injecting `AWS_` environment variables, and validating whether the test data successfully flushes to MinIO using the fallback chain.

**2. Manual Local Verification**
I also successfully verified this end-to-end. Providing credentials exclusively via the environment triggered the fallback correctly and successfully routed Iggy messages to the catalog:

<details>
<summary>Click to view the local verification logs</summary>

```text
# 1. The connector initializes and successfully falls back to default credentials:

2026-04-04T11:28:28.680638Z  INFO connector: connector_target="iggy_connector_iceberg_sink::sink" Opened Iceberg sink connector with ID: 1 for URL: http://rest:8181. No explicit credentials provided, falling back to default credential provider chain
2026-04-04T11:28:28.680661Z  INFO connector: connector_target="iggy_connector_iceberg_sink::sink" Configuring Iceberg catalog with the following config:
-region: us-east-1
-url: http://minio:9000
-store class: S3
-catalog type: REST

2026-04-04T11:28:28.692411Z  INFO connector: connector_target="iggy_connector_iceberg_sink::router::static_router" Static router found 1 tables on iceberg catalog from 1 tables declared
2026-04-04T11:28:28.692612Z  INFO iggy_connectors::sink: Sink container with name: Iceberg sink (iceberg), initialized successfully with ID: 1.

# 2. Sending a test message via CLI to the running server:

$ cargo run --bin iggy -- -u iggy -p password message send test_stream test_topic "{\"id\": 1, \"name\": \"hello_iggy\"}"
Sent messages to topic with ID: test_topic and stream with ID: test_stream

# 3. The connector immediately processes and routes it to Iceberg:

2026-04-04T11:29:54.643126Z  INFO connector: connector_target="iggy_connector_iceberg_sink::router::static_router" Routed 1 messages to iceberg table messages successfully
```
</details>

## AI Usage

1. Which tools? Gemini 3.1 Pro
2. Scope of usage? Paired to implement the `iceberg_sink_uses_default_credential_chain` integration test.
3. How did you verify the generated code works correctly? Verified the test logic and ensured it correctly polls Iceberg snapshots without explicit static access key config. 
4. Can you explain every line of the code if asked? yes

### CODE REVIEW

File: core/connectors/sinks/iceberg_sink/src/sink.rs [hunk 1]
```diff
@@ -30,22 +30,22 @@ use tracing::{debug, error, info};
...
-            .store_secret_access_key
-            .chars()
-            .take(3)
-            .collect::<String>();
-        info!(
-            "Opened Iceberg sink connector with ID: {} for URL: {}, store access key ID: {redacted_store_key}***  store secret: {redacted_store_secret}***",
-            self.id, self.config.uri
-        );
+        if let (Some(store_access_key_id), Some(store_secret_access_key)) = (
+            &self.config.store_access_key_id,
```
Comment (EdgarModesto23) [inline core/connectors/sinks/iceberg_sink/src/sink.rs:34]: If these are optional, maybe It'll be a good to fail if only one of them is present so we can fail early.

File: core/connectors/sinks/iceberg_sink/src/props.rs [hunk 2]
```diff
@@ -30,14 +30,49 @@ pub fn init_props(config: &IcebergSinkConfig) -> Result<HashMap<String, String>,
...
     props.insert("s3.region".to_string(), config.store_region.clone());
-    props.insert(
-        "s3.access-key-id".to_string(),
-        config.store_access_key_id.clone(),
-    );
-    props.insert(
-        "s3.secret-access-key".to_string(),
-        config.store_secret_access_key.clone(),
-    );
+    if let Some(access_key_id) = &config.store_access_key_id {
```
Comment (EdgarModesto23) [inline core/connectors/sinks/iceberg_sink/src/props.rs]: Did you manage to test end-to-end if the rest catalog falls back to the default credential manager if the access-key and secret are not present? If so please add the results in your PR. You can use this docker-compose to have a basic minio/spark-iceberg deployment locally that you can test on.

```yaml
services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    build: spark/
    networks:
      iceberg_net:
    depends_on:
      - rest
      - minio
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001
  rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
networks:
  iceberg_net:
```

File: core/connectors/sinks/iceberg_sink/src/sink.rs (hunk 1 above)
Comment (gomnitrix) [reply core/connectors/sinks/iceberg_sink/src/sink.rs:34]: Thanks for pointing this out. I've update it with an exhaustive `match`, It now logs a error message and immediately returns an `Error::InvalidConfig` to fail fast.

File: core/connectors/sinks/iceberg_sink/src/props.rs (hunk 2 above)
Comment (gomnitrix) [reply core/connectors/sinks/iceberg_sink/src/props.rs]: Thanks for the docker-compose snippet! Here is how I verified it:
1. Automated CI Test: In this PR, I added a new integration test (iceberg_sink_uses_default_credential_chain) specifically to cover this fallback scenario. It has passed in the latest CI run: `PASS [  18.521s] ( 770/1037) integration::mod connectors::iceberg::iceberg_sink::iceberg_sink_uses_default_credential_chain`

2. Manual E2E Testing: Following your suggestion, I also set up the docker environment locally and performed a manual test. Passing the credentials purely via env vars triggered the fallback mechanism correctly, and the messages were routed successfully:
```
# 1. The connector initializes and successfully falls back to default credentials:

2026-04-04T11:28:28.680638Z  INFO connector: connector_target="iggy_connector_iceberg_sink::sink" Opened Iceberg sink connector with ID: 1 for URL: http://rest:8181. No explicit credentials provided, falling back to default credential provider chain
2026-04-04T11:28:28.680661Z  INFO connector: connector_target="iggy_connector_iceberg_sink::sink" Configuring Iceberg catalog with the following config:
-region: us-east-1
-url: http://minio:9000
-store class: S3
-catalog type: REST

2026-04-04T11:28:28.692411Z  INFO connector: connector_target="iggy_connector_iceberg_sink::router::static_router" Static router found 1 tables on iceberg catalog from 1 tables declared
2026-04-04T11:28:28.692612Z  INFO iggy_connectors::sink: Sink container with name: Iceberg sink (iceberg), initialized successfully with ID: 1.

# 2. Sending a test message via CLI to the running server:

$ cargo run --bin iggy -- -u iggy -p password message send test_stream test_topic "{\"id\": 1, \"name\": \"hello_iggy\"}"
Executing send messages to topic with ID: test_topic and stream with ID: test_stream
Sent messages to topic with ID: test_topic and stream with ID: test_stream

# 3. The connector immediately processes and routes it to Iceberg:

2026-04-04T11:29:54.643126Z  INFO connector: connector_target="iggy_connector_iceberg_sink::router::static_router" Routed 1 messages to iceberg table messages successfully
```
I've also added the result into the PR details, hope this looks good to you!

Comment (EdgarModesto23) [reply core/connectors/sinks/iceberg_sink/src/props.rs]: LGTM! Great job

Comment (hubcio) [inline core/connectors/sinks/iceberg_sink/src/props.rs]: `get_props_s3()` handles each credential independently with separate `if let Some(...)` blocks. the partial-credential invariant (both-or-neither) is only enforced in `sink.rs::open()`, but `init_props` is `pub` - a future caller could bypass validation and get a silently half-configured props map. consider making `init_props` `pub(crate)` or adding both-or-neither validation here as defense-in-depth.

File: core/integration/tests/connectors/fixtures/iceberg/container.rs [hunk 3]
```diff
@@ -532,3 +535,39 @@ impl TestFixture for IcebergPreCreatedFixture {
...
+        self.inner.http_client()
+    }
+}
+
+#[async_trait]
+impl TestFixture for IcebergEnvAuthFixture {
+    async fn setup() -> Result<Self, TestBinaryError> {
+        let inner = IcebergPreCreatedFixture::setup().await?;
+        // Set credentials before test server initialization.
+        unsafe {
```
Comment (hubcio) [inline core/integration/tests/connectors/fixtures/iceberg/container.rs]: `unsafe { std::env::set_var }` without cleanup or safety justification. the tokio runtime is already running at this point, so concurrent env reads from other threads are UB. no `Drop` impl means these vars leak into subsequent tests.

the fix is straightforward: add `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY` to the `HashMap` returned by `connectors_runtime_envs()` instead - the harness already passes that map to the child process via `Command::envs()` at `connectors_runtime.rs:157`, eliminating the `unsafe` entirely.

File: core/connectors/sinks/iceberg_sink/src/sink.rs [hunk 4]
```diff
@@ -30,22 +30,32 @@ use tracing::{debug, error, info};
...
+                info!(
+                    "Opened Iceberg sink connector with ID: {} for URL: {}. No explicit credentials provided, falling back to default credential provider chain",
+                    self.id, self.config.uri
+                );
+            }
+            _ => {
+                error!(
+                    "Partially configured Iceberg credentials. You must provide both store_access_key_id and store_secret_access_key, or omit both."
+                );
+                return Err(Error::InvalidConfig);
```
Comment (hubcio) [inline core/connectors/sinks/iceberg_sink/src/sink.rs]: `Error::InvalidConfig` produces a bare "Invalid config" message. `Error::InvalidConfigValue(String)` exists (used by influxdb connectors) and carries a description - use it so the error is self-explanatory without needing to correlate with the `error!()` log above.

File: core/integration/tests/connectors/iceberg/default_credentials_config/config.toml [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+# KIND, either express or implied.  See the License for the
+# specific language governing permissions and limitations
+# under the License.
+
+type = "sink"
+key = "iceberg"
+enabled = true
+version = 0
+name = "Iceberg sink"
+path = "../../target/release/libiggy_connector_iceberg_sink"
```
Comment (hubcio) [inline core/integration/tests/connectors/iceberg/default_credentials_config/config.toml]: `path` points to `target/release` but `ENV_SINK_PATH` always overrides to debug at runtime. not broken, but misleading. this is the same pattern as the original `config.toml` so not introduced by this PR.

File: core/connectors/sinks/iceberg_sink/src/props.rs [hunk 6]
```diff
@@ -30,14 +30,49 @@ pub fn init_props(config: &IcebergSinkConfig) -> Result<HashMap<String, String>,
...
     Ok(props)
 }
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+    use crate::{IcebergSinkConfig, IcebergSinkStoreClass, IcebergSinkTypes};
+
+    #[test]
+    fn test_get_props_s3() {
```
Comment (hubcio) [inline core/connectors/sinks/iceberg_sink/src/props.rs]: test covers both-`None` and both-`Some` but not the mixed case (one `Some`, one `None`). if validation moves into `get_props_s3` per the above comment, this test should verify the error path too.

File: core/integration/tests/connectors/iceberg/iceberg_sink.rs [hunk 7]
```diff
@@ -207,3 +207,50 @@ async fn iceberg_sink_handles_bulk_messages(
...
+
+#[iggy_harness(
+    server(connectors_runtime(config_path = "tests/connectors/iceberg/sink_default_credentials.toml")),
+    seed = seeds::connector_stream
+)]
+async fn iceberg_sink_uses_default_credential_chain(
+    harness: &TestHarness,
+    fixture: IcebergEnvAuthFixture,
+) {
+    let client = harness.root_client().await.unwrap();
```
Comment (hubcio) [inline core/integration/tests/connectors/iceberg/iceberg_sink.rs]: bare `.unwrap()` calls here and at lines 220, 221, 227, 232 - the existing tests in this file consistently use `.expect("...")` with context messages.

File: core/connectors/sinks/iceberg_sink/src/props.rs (hunk 2 above)
Comment (gomnitrix) [reply core/connectors/sinks/iceberg_sink/src/props.rs]: I've added the both-or-neither validation to `get_props_s3`. Thanks for pointing out!

File: core/integration/tests/connectors/iceberg/default_credentials_config/config.toml (hunk 5 above)
Comment (gomnitrix) [reply core/integration/tests/connectors/iceberg/default_credentials_config/config.toml]: I've updated the path to `debug` in this config to match the actual test environment and avoid confusion.

File: core/integration/tests/connectors/iceberg/iceberg_sink.rs (hunk 7 above)
Comment (gomnitrix) [reply core/integration/tests/connectors/iceberg/iceberg_sink.rs]: Fixed. I replaced all `unwrap()` calls with `expect()` to provide better error context.

File: core/connectors/sinks/iceberg_sink/src/sink.rs (hunk 4 above)
Comment (gomnitrix) [reply core/connectors/sinks/iceberg_sink/src/sink.rs]: I've switched to `Error::InvalidConfigValue`, I think it's now much cleaner!

File: core/integration/tests/connectors/fixtures/iceberg/container.rs (hunk 3 above)
Comment (gomnitrix) [reply core/integration/tests/connectors/fixtures/iceberg/container.rs]: Yes, this is a serious issue. I missed the concurrency risks while trying to figure out how the test environment handles variables. I'll spend more time digging into the implementation to avoid similar mistakes in the future. I've fixed it and thanks for the heads-up!

File: core/connectors/sinks/iceberg_sink/src/props.rs (hunk 6 above)
Comment (gomnitrix) [reply core/connectors/sinks/iceberg_sink/src/props.rs]: Updated the unit tests to cover the partial credential scenarios. Since adding the new cases made the test a bit long and bloated, I also split it up. Thanks!
