### PR TITLE
fix(go): correct buffer size for CreateUser and UpdatePermissions serialization

### LINKED ISSUE #2981: Go SDK: CreateUser omits mandatory permissions_len field when permissions are nil
The Rust wire format for `CreateUser` always includes `permissions_len:u32_le` on the wire, even when `has_permissions=0`. The server-side decoder unconditionally reads these 4 bytes (see [create_user.rs#L82-L83](https://github.com/apache/iggy/blob/master/core/binary_protocol/src/requests/users/create_user.rs#L82-L83)), and the Rust encoder always writes them (see [create_user.rs#L61-L62](https://github.com/apache/iggy/blob/master/core/binary_protocol/src/requests/users/create_user.rs#L61-L62)).

In the Go SDK (`foreign/go/internal/command/user.go`), the nil-permissions branch only writes `has_permissions=0` (1 byte) and skips the 4-byte `permissions_len=0`:

```
} else {
    bytes[position] = byte(0) // writes flag only, no permissions_len
}
```

The server will try to read 4 bytes that aren't there, causing a parse failure or reading into the next message.

Fix: Write permissions_len=0 (4 zero bytes) after the flag in the else branch, and add 4 to the base capacity.

### PR DESCRIPTION
**Pull request by atharvalade**
## Which issue does this PR close?

Closes #2981

## Rationale

The Go SDK's `CreateUser` and `UpdatePermissions` commands had incorrect buffer size calculations for the `has_permissions` flag byte, causing a 1-byte over-allocation in `CreateUser` (non-nil path) and an index-out-of-bounds panic in `UpdatePermissions` (nil path).

## What changed?

Both `CreateUser.MarshalBinary()` and `UpdatePermissions.MarshalBinary()` double-counted the 1-byte `has_permissions` flag in the non-nil branch, while `UpdatePermissions` omitted it entirely from the base allocation (causing a panic when permissions were nil).

The fix accounts for the `has_permissions` byte exactly once: in `CreateUser` it is part of the base capacity `4`, and in `UpdatePermissions` it is now added to the base `length`. The `+1` was removed from the non-nil branch in both methods. Unit tests were added for all four cases (nil/non-nil x CreateUser/UpdatePermissions).

## Local Execution

- Passed
- Pre-commit hooks ran (trailing-whitespace, trailing-newline, license-headers all pass; `go test ./...` all pass; `gofmt` clean; `go vet` clean)

## AI Usage

1. Opus 4.6
2. Minimal AI used
3. Yes, all code can be explained

### CODE REVIEW

**Review by hubcio — APPROVED** [review]

File: foreign/go/internal/command/user.go [hunk 1]
```diff
@@ -116,10 +116,10 @@ func (u *UpdatePermissions) MarshalBinary() ([]byte, error) {
 	if err != nil {
 		return nil, err
 	}
-	length := len(userIdBytes)
+	length := len(userIdBytes) + 1
 
 	if u.Permissions != nil {
-		length += 1 + 4 + u.Permissions.Size()
```
Comment (spetz) [inline foreign/go/internal/command/user.go:122]: This is incorrect, as the byte on the front sets the flag whether permissions are present or not (1 or 0 as the value).

Actually, it should work like this (this byte is required).

```go
length := len(userIdBytes) + 1  // +1 for has_permissions flag
if u.Permissions != nil {
    length += 4 + u.Permissions.Size()
}
```

**Review by spetz — APPROVED** [review]

**Review by spetz — CHANGES_REQUESTED** [review]
Please fix one issue (accidentally approved before).

**Review by spetz — APPROVED** [review]

**Review by hubcio — APPROVED** [review]
