### PR TITLE
fix(consensus): prevent UB from untrusted bytes interpreted as enum discriminants in consensus headers                                                                                    

### LINKED ISSUE #2878: unsafe impl Pod is unsound for consensus headers containing Command2 and Operation enums
### Bug description

`bytemuck::Pod` requires that every possible bit pattern is a valid instance of the type.

  - `Command2` defines discriminants `0..=12` only (13 of 256 possible u8 values)
  - `Operation` defines discriminants `0, 128..=147, 160..=161, 200` (23 of 256 possible u8 values)

When `bytemuck::from_bytes::<PrepareHeader>(&buf)` is called on a network buffer containing e.g. command = `0xFF`, Rust materializes a Command2 with an invalid discriminant. This is UB and the compiler is free to assume enum fields always hold valid discriminants. 

### Deployment

Not applicable

### Versions

_No response_

### Hardware / environment

_No response_

### Sample code

```rust
use bytemuck::{Pod, Zeroable};

/// Only discriminants 0, 1, 2 are valid.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
enum Command {
    Ping = 0,
    Pong = 1,
    Request = 2,
}

#[derive(Debug, Clone, Copy)]
#[repr(C)]
struct Header {
    command: Command,
}

unsafe impl Zeroable for Header {}
unsafe impl Pod for Header {}

fn main() {
    let buf: [u8; 1] = [255];

    let header: &Header = bytemuck::from_bytes(&buf);

    match header.command {
        Command::Ping => println!("ping"),
        Command::Pong => println!("pong"),
        Command::Request => println!("request"),
    }

    println!("command == Ping? {}", header.command == Command::Ping);
    println!("raw byte: 0x{:02X}", header.command as u8);
}
```

### Logs

_No response_

### Iggy server config

_No response_

### Reproduction

Try this MWE on Rust Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=2e4f80fe9eb435682b0ede6b7c3c95b8

And run the above example using Miri to see it throw error.

### PR DESCRIPTION
**Pull request by krishvishal**
Closes #2878

## Rationale

Consensus headers previously stored `Command2` and `Operation` enum values directly in repr(C) structs. This is unsound for consensus header  structs: arbitrary bytes from the network are reinterpreted as enum discriminants without validation, which is undefined behavior in Rust.

## What changed?

  - Change `command` and `operation` fields in all consensus headers from enum types (`Command2`, `Operation`) to raw `u8` to prevent UB when interpreting untrusted bytes from the network as Rust enum discriminants.
  - Add `TryFrom<u8>` impls for `Command2` and `Operation` with proper error variants (`InvalidCommandByte`, `InvalidOperationByte`) in `ConsensusError`.
  - Fix `dispatch_request` to return `Result<Receiver<R>, ConsensusError>` instead of silently dropping unrecognized messages.

### CODE REVIEW

File: core/common/src/types/consensus/header.rs [hunk 1]
```diff
@@ -449,19 +517,21 @@ impl ConsensusHeader for PrepareOkHeader {
     const COMMAND: Command2 = Command2::PrepareOk;
 
     fn operation(&self) -> Operation {
```
Comment (numinnex) [inline core/common/src/types/consensus/header.rs:452]: In the solution that I've provided we wouoldn't need to use the `TryFrom`, as we would store the enums directly there, but rather the transistion/creation part is where validation would happen.

File: core/common/src/types/consensus/header.rs [hunk 2]
```diff
@@ -449,19 +517,21 @@ impl ConsensusHeader for PrepareOkHeader {
...
-        self.operation
+        Operation::try_from(self.operation).expect("validate() must be called first")
     }
     fn command(&self) -> Command2 {
```
Comment (numinnex) [inline core/common/src/types/consensus/header.rs:455]: Same for command

File: core/common/src/types/consensus/header.rs [hunk 3]
```diff
@@ -124,6 +153,40 @@ pub enum Operation {
...
+            141 => Ok(Operation::CreateUser),
+            142 => Ok(Operation::UpdateUser),
+            143 => Ok(Operation::DeleteUser),
+            144 => Ok(Operation::ChangePassword),
+            145 => Ok(Operation::UpdatePermissions),
+            146 => Ok(Operation::CreatePersonalAccessToken),
+            147 => Ok(Operation::DeletePersonalAccessToken),
+            160 => Ok(Operation::SendMessages),
+            161 => Ok(Operation::StoreConsumerOffset),
+            200 => Ok(Operation::Reserved),
```
Comment (numinnex) [inline core/common/src/types/consensus/header.rs]: We have both `Operation::Default` and `Operation::Reserved`, I don't think so there is a good reason for that, rather we should make Default = Reserved

Comment (numinnex) [reply core/common/src/types/consensus/header.rs]: I see, that `Default` is used by the `fn operation(&self) -> Operation` as default implementation, I think we should return reserved in that case as that's what it's purpose is.

File: core/common/src/types/consensus/header.rs (hunk 1 above)
Comment (krishvishal) [reply core/common/src/types/consensus/header.rs:452]: Done.

File: core/common/src/types/consensus/header.rs (hunk 2 above)
Comment (krishvishal) [reply core/common/src/types/consensus/header.rs:455]: Done.

File: core/common/src/types/consensus/header.rs (hunk 3 above)
Comment (krishvishal) [reply core/common/src/types/consensus/header.rs]: Done.

File: core/common/src/types/consensus/header.rs [hunk 4]
```diff
@@ -201,14 +276,15 @@ impl ConsensusHeader for GenericHeader {
     const COMMAND: Command2 = Command2::Reserved;
 
     fn operation(&self) -> Operation {
-        Operation::Default
+        Operation::Reserved
     }
 
     fn command(&self) -> Command2 {
```
Comment (numinnex) [inline core/common/src/types/consensus/header.rs:217]: Do we need to store teh command as u8 on the header, instead of `Command2` enum ?

Comment (numinnex) [reply core/common/src/types/consensus/header.rs:217]: We construct the header thgrough the `try_from_bytes` method from bytemuck, which has the validation

Comment (krishvishal) [reply core/common/src/types/consensus/header.rs:217]: Done.
