### PR TITLE
fix(sdk): allow hostnames in server address configuration

### LINKED ISSUE #2882: Rust SDK: Support DNS addresses in client
### Bug description

Not sure if it's a bug or a request for enhacement.

## Problem
During connection build via the client, if an ip addresses is passed (e.g. `127.0.0.1`), then the client tries to connect. When passing a dns entry (e.g. `host.docker.internal`), it raises `Invalid IP address: host.docker.internal:8090`

## Desired Behaviour
When connecting, even passing a `dns` entry should result in a successful connection (assuming that the entry is correct and matches to an active ip address)

## Notes
Considering [https://stackoverflow.com/questions/28255861/convert-string-to-socketaddr](https://stackoverflow.com/questions/28255861/convert-string-to-socketaddr) it seems that there are two ways of establishing a connection: one via ip and one via `dns` entry. Not sure if this functionality has not been supported due to the added complexity, but in some cases it could be quite handy

### Deployment

None

### Versions

_No response_

### Hardware / environment

_No response_

### Sample code

_No response_

### Logs

_No response_

### Iggy server config

_No response_

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by felixfaisal**
## Which issue does this PR close?

Closes #2882

## Rationale

Server address validation previously required a literal socket address, preventing the use of DNS hostnames. This change allows hostnames (e.g., `localhost:8080`) in addition to IP addresses.

## What changed?

Server address validation previously relied on `SocketAddr` parsing, which only accepts literal IP addresses and rejected DNS hostnames (e.g., `localhost:8080`). This prevented using hostnames when configuring client connections.

Validation now uses `ToSocketAddrs`, which performs address resolution and returns the list of socket addresses for a given host. `TcpStream::connect(...)` already performs this resolution internally and attempts to connect to each resolved address.

## Local Execution

- Passed
- Pre-commit hooks ran

## AI Usage

If AI tools were used, please answer:
1. Which tools? ChatGPT free version
2. Scope of usage? Write documentations like comments 
3. How did you verify the generated code works correctly? 
- I built the code using `cargo build` 
- I ran the unit tests under `TCPConfigBuilder` and added an additional unit test, also modifying another
- I then ran the server and ran the examples 
4. Can you explain every line of the code if asked? Yup

### CODE REVIEW

File: core/common/src/utils/net.rs [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+    // Reject bare IPv6 addresses
+    if host.contains(':') {
+        return Err(IggyError::InvalidIpAddress(
+            host.to_string(),
+            port_str.to_string(),
+        ));
+    }
+
+    port_str
+        .parse::<u16>()
```
Comment (hubcio) [inline core/common/src/utils/net.rs]: port 0 passes validation here since `0u16` parses fine, but it's not a valid server address port. worth rejecting explicitly:

```rust
let port = port_str.parse::<u16>().map_err(|_| ...)?;
if port == 0 {
    return Err(IggyError::InvalidIpAddress(host.to_string(), port_str.to_string()));
}
```

same applies to the ipv6 branch (line 48).

File: core/common/src/utils/net.rs [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+
+        return Ok(());
+    }
+    // hostname:port or IPv4:port — rsplit_once to split at last colon
+    let (host, port_str) = addr.rsplit_once(':').ok_or(IggyError::InvalidIpAddress(
+        addr.to_string(),
+        "".to_string(),
+    ))?;
+
+    if host.is_empty() {
```
Comment (hubcio) [inline core/common/src/utils/net.rs]: currently only empty host and bare colons are rejected, but any other characters pass - e.g. `"!!!:8080"` is accepted. would be good to add basic hostname character validation per RFC 952/1123 (alphanumeric, hyphens, dots) to catch obviously invalid addresses at config time rather than deferring everything to DNS resolution at connect time.

File: core/common/src/utils/net.rs (hunk 1 above)
Comment (felixfaisal) [reply core/common/src/utils/net.rs]: Updated to check for `0` , and added a unit test for it. ✅

File: core/common/src/utils/net.rs (hunk 2 above)
Comment (felixfaisal) [reply core/common/src/utils/net.rs]: Created a separate function, to check if valid IPv4 address and if not check if valid hostname, added a couple of unit tests using claude. ✅  
I was thinking if i should use regex or not, and ultimately decided to do it this way.

File: core/common/src/types/configuration/tcp_config/tcp_client_config_builder.rs [hunk 3]
```diff
@@ -105,11 +104,7 @@ impl TcpClientConfigBuilder {
     /// Builds the TCP client configuration.
     pub fn build(self) -> Result<TcpClientConfig, IggyError> {
         let addr = self.config.server_address.trim();
```
Comment (hubcio) [inline core/common/src/types/configuration/tcp_config/tcp_client_config_builder.rs]: `build()` validates the trimmed `addr` but returns `self.config` with the original untrimmed `server_address`. if someone passes `" localhost:8090 "`, validation passes but `TcpStream::connect` later gets the whitespace-padded string. same issue in `websocket_client_config_builder.rs`.

fix: `self.config.server_address = self.config.server_address.trim().to_string();` before validating.

File: core/common/src/utils/net.rs [hunk 4]
```diff
@@ -0,0 +1,291 @@
...
+/// Accepted formats:
+/// - `hostname:port` (e.g. `iggy-server:8090`, `localhost:8090`)
+/// - `ipv4:port` (e.g. `127.0.0.1:8090`)
+/// - `[ipv6]:port` (e.g. `[::1]:8090`)
+///
+/// Rejected formats:
+/// - Bare IPv6 without brackets (e.g. `::1:8080`) — ambiguous due to colons
+/// - Missing port (e.g. `localhost`)
+/// - Invalid port (e.g. `localhost:abc`, `localhost:65536`)
+pub fn parse_server_address(addr: &str) -> Result<(), IggyError> {
```
Comment (hubcio) [inline core/common/src/utils/net.rs]: the function name says "parse" but it returns `Result<(), IggyError>` - it validates, it doesn't parse anything. `validate_server_address` would be more accurate for a public API, or return a structured type like `(host, port)` to make the parse useful.

File: core/common/src/utils/net.rs [hunk 5]
```diff
@@ -0,0 +1,291 @@
...
+    if let Some(rest) = addr.strip_prefix('[') {
+        // Bracketed IPv6: "[::1]:port"
+        let close = rest.find(']').ok_or(IggyError::InvalidIpAddress(
+            addr.to_string(),
+            "".to_string(),
+        ))?;
+        let ipv6_str = &rest[0..close];
```
Comment (hubcio) [inline core/common/src/utils/net.rs]: `&rest[0..close]` - the `0..` is redundant, `&rest[..close]` is idiomatic.

File: core/sdk/src/prelude.rs [hunk 6]
```diff
@@ -63,6 +63,7 @@ pub use iggy_common::{
     TcpClientReconnectionConfig, Topic, TopicDetails, TopicPermissions, TransportEndpoints,
     TransportProtocol, UserId, UserStatus, Validatable, WebSocketClientConfig,
     WebSocketClientConfigBuilder, WebSocketClientReconnectionConfig, defaults, locking,
+    parse_server_address,
```
Comment (hubcio) [inline core/sdk/src/prelude.rs]: `parse_server_address` is a low-level validation utility. the builders already call it internally, so SDK consumers rarely need it directly. consider keeping it importable from `iggy_common` without putting it in the prelude - prelude is for iggy users.

File: core/common/src/utils/mod.rs [hunk 7]
```diff
@@ -23,6 +23,7 @@ pub(crate) mod crypto;
 pub(crate) mod duration;
 pub(crate) mod expiry;
 pub(crate) mod hash;
+pub mod net;
```
Comment (hubcio) [inline core/common/src/utils/mod.rs]: `pub mod net` but the sibling modules are `pub(crate)`. since only `parse_server_address` is re-exported in `lib.rs`, this could be `pub(crate) mod net` to match the pattern.

File: core/common/src/types/configuration/tcp_config/tcp_client_config_builder.rs (hunk 3 above)
Comment (felixfaisal) [reply core/common/src/types/configuration/tcp_config/tcp_client_config_builder.rs]: Updated ✅

File: core/common/src/utils/net.rs (hunk 4 above)
Comment (felixfaisal) [reply core/common/src/utils/net.rs]: Updated to `validate_server_address` ✅

File: core/common/src/utils/net.rs (hunk 5 above)
Comment (felixfaisal) [reply core/common/src/utils/net.rs]: Updated ✅

File: core/sdk/src/prelude.rs (hunk 6 above)
Comment (felixfaisal) [reply core/sdk/src/prelude.rs]: Updated ✅

File: core/common/src/utils/mod.rs (hunk 7 above)
Comment (felixfaisal) [reply core/common/src/utils/mod.rs]: Updated ✅

File: core/common/src/utils/net.rs [hunk 8]
```diff
@@ -0,0 +1,291 @@
...
+            && label.len() <= 63
+            && label
+                .chars()
+                .next()
+                .is_some_and(|c| c.is_ascii_alphanumeric())
+            && label
+                .chars()
+                .last()
+                .is_some_and(|c| c.is_ascii_alphanumeric())
+            && label.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
```
Comment (hubcio) [inline core/common/src/utils/net.rs]: underscores in hostnames are rejected here (only allows alphanumeric and `-`). while RFC 1123 technically forbids underscores, they are widespread in practice - Docker Compose v1 projects, custom container names, SRV records like `_svc._tcp.example.com`. since the pr's primary goal is enabling hostname-based addresses for container environments, consider allowing underscores (`|| c == '_'`). at minimum, document the restriction.

File: core/common/src/utils/net.rs [hunk 9]
```diff
@@ -0,0 +1,291 @@
...
+/// Rejected formats:
+/// - Bare IPv6 without brackets (e.g. `::1:8080`) — ambiguous due to colons
+/// - Missing port (e.g. `localhost`)
+/// - Invalid port (e.g. `localhost:abc`, `localhost:65536`)
+pub fn validate_server_address(addr: &str) -> Result<(), IggyError> {
+    if let Some(rest) = addr.strip_prefix('[') {
+        // Bracketed IPv6: "[::1]:port"
+        let close = rest.find(']').ok_or(IggyError::InvalidIpAddress(
+            addr.to_string(),
+            "".to_string(),
```
Comment (hubcio) [inline core/common/src/utils/net.rs]: when port is unknown (e.g., missing closing bracket), `""` as the port field produces error messages with a dangling colon like `Invalid IP address: [::1:`. consider passing the full original `addr` for context, or a placeholder like `<missing>`. also, `String::new()` is idiomatic over `"".to_string()` (zero-alloc). same issue at lines 47, 67.

File: core/common/src/utils/net.rs (hunk 8 above)
Comment (felixfaisal) [reply core/common/src/utils/net.rs]: Updated ✅

File: core/common/src/utils/net.rs (hunk 9 above)
Comment (felixfaisal) [reply core/common/src/utils/net.rs]: Updated ✅

**Review by mmodzelewski — APPROVED** [review]

**Review by spetz — APPROVED** [review]
