### PR TITLE
fix(go): correct Permissions serialization and add unit tests

### LINKED ISSUE #2980: Go SDK: CreatePersonalAccessToken writes expiry as uint32 at wrong offset in uint64 field
The binary wire protocol defines the `CreatePersonalAccessToken` format as `[name_len:u8][name:N][expiry:u64_le]`  the expiry is an 8-byte little-endian uint64 (see [create_personal_access_token.rs#L25](https://github.com/apache/iggy/blob/master/core/binary_protocol/src/requests/personal_access_tokens/create_personal_access_token.rs#L25)).

The Go SDK gets this wrong in two ways:

1. The `Expiry` field is declared as `uint32` instead of `uint64`
2. `MarshalBinary()` uses `PutUint32(bytes[len(bytes)-4:], c.Expiry)` which writes 4 bytes at offset `1 + len(name) + 4` instead of writing 8 bytes at offset `1 + len(name)`

This leaves 4 zero bytes between the name and the actual expiry value. The server reads all 8 bytes as a single `u64_le`, so the expiry ends up in the high 32 bits — effectively `value << 32`. Any non-zero expiry (e.g. 3600 for 1 hour) gets interpreted as ~490,000 years, making tokens silently never expire.

**Fix:** In `foreign/go/internal/command/access_token.go`, change the field type to `uint64` and replace the `PutUint32` call with `PutUint64(bytes[1+len(c.Name):], c.Expiry)`.

### PR DESCRIPTION
**Pull request by saie-ch**
## Bugs Fixed:                                                                                                                                     
                                                                                                                                                     
  **Permissions.MarshalBinary()** - Fixed missing continuation flags between stream/topic entries. The serializer wasn't writing 1-byte flags        
  (1=has_next, 0=no_next) after each entry, causing the server to incorrectly parse permission data and potentially grant wrong permissions. Also    
  added `len() > 0` checks to match Rust SDK's behavior of skipping empty maps.                                                                      
                                                                                                                                                     


  **Note:** Does NOT fix #2980, #2981, #2982 (missing 4-byte permissions_len field before permissions data - those are separate issues found during the review of #2973).

### CODE REVIEW

File: foreign/go/contracts/users_test.go [hunk 1]
```diff
@@ -0,0 +1,232 @@
...
+
+		if hasNextStream == 0 {
+			break
+		}
+	}
+
+	if streamsFound != 2 {
+		t.Errorf("Expected 2 streams, found %d", streamsFound)
+	}
+}
```
Comment (chengxilo) [inline foreign/go/contracts/users_test.go:623]: @saie-ch The test should verify that each attribute of Permissions is encoded correctly. Right now, those checks are being skipped. This only validates the basic frame structure (e.g., continuation flags and the size of each part). It would be better to also read back the encoded content and confirm that it matches the values you originally provided.

Comment (ryankert01) [reply foreign/go/contracts/users_test.go:623]: +1

File: foreign/go/contracts/users_test.go
Comment (chengxilo) [inline foreign/go/contracts/users_test.go:48]: I'm sorry that I keep asking you to modify your code.

However, your changes actually doesn't address the problem. If in the future I swaped the position of `ManageServers` and `ManageUsers` when encoding, this test won't know I am wrong.


To better desribe the problem, consider you have this struct.

```go
Foo {
    A bool,
    B bool,
    C bool,
}
```

You wrot a function to encode it.

```go
func (f Foo) MarshalBinary() ([]byte, error) {
    return []byte{
        boolToByte(f.A), 
        boolToByte(f.B), 
        boolToByte(f.C),
    }
}
```

You wrote a test and here is your test case:
```go
input: Foo {
    A: true,
    B: false,
    C: true
}
want: []byte {1, 0, 1}
```
And you can get a []byte {1, 0, 1}, you are 100% correct.

However, if I write the function like this:

```go
func (f Foo) MarshalBinary() ([]byte, error) {
    return []byte{
        boolToByte(f.C), 
        boolToByte(f.B), 
        boolToByte(f.A),
    }
}
```

I will still get []byte {1, 0, 1}, I can still pass the test, but actually it's wrong.

So you probably want to make sure every single field are correctly encoded.

Consider  make a bigger test case:
```go
{ 
    input: Foo {
        A: true
    },
    want: []byte{1,0,0}
},
{
    input: Foo {
        B: true
    },
    want: []byte{0,1,0}
},
{
    input: Foo {
        C: true
    },
    want: []byte{0,0,1}
}
```

Comment (chengxilo) [inline foreign/go/contracts/users_test.go:71]: same here

**Review by chengxilo — CHANGES_REQUESTED** [review]

File: foreign/go/contracts/users_test.go
Comment (saie-ch) [reply foreign/go/contracts/users_test.go:48]: No problem @chengxilo, happy to modify until it's correct. Can you check now?
